server:
  port: 8080
  context-path: /client1

security:
  oauth2:
    client:
      client-id: cheng1
      client-secret: chengSecret1
      # 授权地址
      user-authorization-uri: http://127.0.0.1:9999/server/oauth/authorize
      # 请求令牌地址
      access-token-uri: http://127.0.0.1:9999/server/oauth/token
    resource:
      jwt:
        # jwt 获取
        key-uri: http://127.0.0.1:9999/server/oauth/token_key

